In [1]:
import numpy as np

In [2]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print(X)

[[ -8.36487835   7.18986519  24.93288    ...  -5.56034589   5.81888526
    8.50548767]
 [ -2.3433979   14.30358289 -12.29086292 ... -23.76783703  -4.86318567
    1.471135  ]
 [ 12.76157203   6.9889099  -18.3220964  ...  10.26718994   1.45961661
  -24.13426169]
 ...
 [ -5.67224513  -1.43837927 -10.55079877 ...  -4.24958296  -4.77586913
  -13.16129985]
 [ 15.12049886 -16.30395573   9.77855628 ...  -0.17022898   5.51458267
   -5.59204556]
 [  4.3539907    7.82350717   6.3710704  ...  -4.45217665   3.27107063
    1.34704383]]


In [4]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m)  / std)
print(X_norm)

[[-0.94709592  0.55998352  2.37453256 ... -0.649064    0.48169963
   0.80994968]
 [-0.34391238  1.30104962 -1.31461193 ... -2.42967341 -0.61701702
   0.10761782]
 [ 1.16918217  0.53904915 -1.91235116 ...  0.89879666  0.03332206
  -2.44890538]
 ...
 [-0.67736955 -0.33885725 -1.14215887 ... -0.52087738 -0.60803598
  -1.35333042]
 [ 1.40548051 -1.88746731  0.87262852 ... -0.1219352   0.45040024
  -0.5975923 ]
 [ 0.32697821  0.62599268  0.53492181 ... -0.54069011  0.21964124
   0.09522817]]


In [5]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [7]:
r = np.sum(Z, axis=1)
print (np.nonzero(r > 10))

(array([1, 4, 5], dtype=int64),)


In [8]:
A = np.eye(3)
B = np.eye(3)
print (A)
print (B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
A_vstack_B = np.vstack((A, B))
print(A_vstack_B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
